name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Build + quality gates (tests skipped for now)
      - name: Verify (format, lint, static analysis, package)
        run: mvn -B -ntp spotless:check checkstyle:check spotbugs:check package -DskipTests
